import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { I18nProvider } from "@/i18n/context";

// Dynamic import of dictionaries to avoid bundling all of them in the client initially
const dictionaries = {
  en: () =>
    import("@/i18n/dictionaries/en.json").then((module) => module.default),
  es: () =>
    import("@/i18n/dictionaries/es.json").then((module) => module.default),
  fr: () =>
    import("@/i18n/dictionaries/fr.json").then((module) => module.default),
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const locale = cookieStore.get("NEXT_LOCALE")?.value || "en";

  // Await the dictionary
  const dictionary = await (
    dictionaries[locale as keyof typeof dictionaries] || dictionaries.en
  )();

  return (
    <html lang={locale}>
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${inter.variable} font-display antialiased bg-clear-day text-nordic`}
      >
        <I18nProvider dictionary={dictionary} locale={locale}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
